## Traefik Static Configuration
## Used with traefik-compose.yml
## Place this file in the same directory as traefik-compose.yml

global:
  checkNewVersion: false
  sendAnonymousUsage: false

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: frontend
    watch: true
    swarmMode: false
  file:
    filename: /traefik.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "your-email@valor-ecosystem.nl"
      storage: /letsencrypt/acme.json
      httpChallenge:
        entrypoint: web
      # Production = https://acme-v02.api.letsencrypt.org/directory
      # Staging = https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory

log:
  level: INFO
  filePath: /var/log/traefik.log

accessLog:
  filePath: /var/log/traefik-access.log
  format: common

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
